# Generated by Django 4.2.4 on 2023-08-31 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('users', '0002_siteuser_avatar_siteuser_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='favorites',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, to='artists.album'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='follows',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
