# Generated by Django 5.0.4 on 2024-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_siteuser_options_siteuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='follows',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
    ]
