# Generated by Django 5.0.4 on 2024-04-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_siteuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='favorite_albums',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='slug',
        ),
    ]
