# Generated by Django 5.0.4 on 2024-04-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('users', '0007_remove_siteuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(default='static/img/default_user.png', upload_to='users/media/images/avatars/'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, to='artists.album'),
        ),
    ]
