# Generated by Django 4.2.4 on 2023-08-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_slug',
            new_name='slug',
        ),
    ]
