# Generated by Django 4.2.4 on 2023-08-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album', to='albums.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='/static/default_album.png', upload_to=''),
        ),
    ]
