# Generated by Django 4.2.4 on 2023-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_artist_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='static/default_album.png', upload_to='static/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
