# Generated by Django 4.2.4 on 2023-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.TimeField(default='0:00'),
        ),
        migrations.AddField(
            model_name='song',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
