# Generated by Django 4.2.4 on 2023-08-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_alter_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='albums/static/img/default_album.png', upload_to='albums/media/images/'),
        ),
    ]
