# Generated by Django 4.2.4 on 2023-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='static/img/default_album.png', upload_to='albums/media/images/'),
        ),
    ]
